---
abstract: 'A simple interface to the L<Spotify Web API|https://developer.spotify.com/web-api/> '
author:
  - 'Nick Langridge <nickl@cpan.org>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Spotify
requires:
  Data::Dumper: 0
  IO::File: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Method::Signatures: 0
  Moo: 0
  URI::QueryParam: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/nicklangridge/WebService-Spotify
version: 1.001
